export const sampleOrders = [
  {
    domain: "Fashion",
    city: "Chennai",
    state: "Tamil Nadu",
    category: "Fashion",
    status: "Accepted",
    paymentType: "ON-FULFILLMENT",
    buyerFinderFee: 9,
    orderValue: 6503,
    pendingAmount: 6494,
    deliveryPincode: 704140,
    np: "TechWorld",
    createdAt: "09 Sep 2024",
  },

  {
    domain: "Fashion",
    city: "Chennai",
    state: "Tamil Nadu",
    category: "Fashion",
    status: "Accepted",
    paymentType: "POST-FULFILLMENT",
    buyerFinderFee: 30,
    orderValue: 7858,
    pendingAmount: 7828,
    deliveryPincode: 961194,
    np: "GroceryExpress",
    createdAt: "17 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Noida",
    state: "Uttar Pradesh",
    category: "Fashion",
    status: "Accepted",
    paymentType: "PRE-FULFILLMENT",
    buyerFinderFee: 6,
    orderValue: 7806,
    pendingAmount: 7800,
    deliveryPincode: 190524,
    np: "TechWorld",
    createdAt: "18 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Noida",
    state: "Uttar Pradesh",
    category: "Fashion",
    status: "Accepted",
    paymentType: "ON-ORDER",
    buyerFinderFee: 26,
    orderValue: 5894,
    pendingAmount: 5868,
    deliveryPincode: 967309,
    np: "GroceryExpress",
    createdAt: "20 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Hyderabad",
    state: "Telangana",
    category: "Fashion",
    status: "Created",
    paymentType: "ON-FULFILLMENT",
    buyerFinderFee: 19,
    orderValue: 4576,
    pendingAmount: 4557,
    deliveryPincode: 370235,
    np: "GroceryExpress",
    createdAt: "26 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Noida",
    state: "Uttar Pradesh",
    category: "Fashion",
    status: "Created",
    paymentType: "POST-FULFILLMENT",
    buyerFinderFee: 13,
    orderValue: 1597,
    pendingAmount: 1584,
    deliveryPincode: 967499,
    np: "TechWorld",
    createdAt: "14 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Hyderabad",
    state: "Telangana",
    category: "Fashion",
    status: "Created",
    paymentType: "PRE-FULFILLMENT",
    buyerFinderFee: 30,
    orderValue: 4936,
    pendingAmount: 4906,
    deliveryPincode: 138681,
    np: "TechWorld",
    createdAt: "13 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Delhi",
    state: "Delhi",
    category: "Fashion",
    status: "Created",
    paymentType: "ON-ORDER",
    buyerFinderFee: 22,
    orderValue: 6928,
    pendingAmount: 6906,
    deliveryPincode: 642803,
    np: "FashionHub",
    createdAt: "30 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Noida",
    state: "Uttar Pradesh",
    category: "Fashion",
    status: "In-Progress",
    paymentType: "ON-FULFILLMENT",
    buyerFinderFee: 5,
    orderValue: 2181,
    pendingAmount: 2176,
    deliveryPincode: 490955,
    np: "FashionHub",
    createdAt: "17 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Mumbai",
    state: "Maharashtra",
    category: "Fashion",
    status: "In-Progress",
    paymentType: "POST-FULFILLMENT",
    buyerFinderFee: 26,
    orderValue: 9008,
    pendingAmount: 8982,
    deliveryPincode: 892752,
    np: "FashionHub",
    createdAt: "20 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Delhi",
    state: "Delhi",
    category: "Fashion",
    status: "In-Progress",
    paymentType: "PRE-FULFILLMENT",
    buyerFinderFee: 27,
    orderValue: 5486,
    pendingAmount: 5459,
    deliveryPincode: 182008,
    np: "RetailNet",
    createdAt: "20 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Chennai",
    state: "Tamil Nadu",
    category: "Fashion",
    status: "In-Progress",
    paymentType: "ON-ORDER",
    buyerFinderFee: 20,
    orderValue: 8075,
    pendingAmount: 8055,
    deliveryPincode: 656136,
    np: "TechWorld",
    createdAt: "17 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Bengaluru",
    state: "Karnataka",
    category: "Fashion",
    status: "Completed",
    paymentType: "ON-FULFILLMENT",
    buyerFinderFee: 30,
    orderValue: 140,
    pendingAmount: 110,
    deliveryPincode: 837043,
    np: "FashionHub",
    createdAt: "18 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Mumbai",
    state: "Maharashtra",
    category: "Fashion",
    status: "Completed",
    paymentType: "POST-FULFILLMENT",
    buyerFinderFee: 15,
    orderValue: 2179,
    pendingAmount: 2164,
    deliveryPincode: 431807,
    np: "TechWorld",
    createdAt: "02 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Chennai",
    state: "Tamil Nadu",
    category: "Fashion",
    status: "Completed",
    paymentType: "PRE-FULFILLMENT",
    buyerFinderFee: 18,
    orderValue: 8149,
    pendingAmount: 8131,
    deliveryPincode: 332618,
    np: "FoodDelivery",
    createdAt: "14 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Bengaluru",
    state: "Karnataka",
    category: "Fashion",
    status: "Completed",
    paymentType: "ON-ORDER",
    buyerFinderFee: 18,
    orderValue: 2931,
    pendingAmount: 2913,
    deliveryPincode: 106883,
    np: "RetailNet",
    createdAt: "19 Sep 2024",
  },
  {
    domain: "Fashion",
    city: "Noida",
    state: "Uttar Pradesh",
    category: "Fashion",
    status: "Cancelled",
    paymentType: "ON-FULFILLMENT",
    buyerFinderFee: 23,
    orderValue: 8395,
    pendingAmount: 0,
    deliveryPincode: 289708,
    np: "FashionHub",
    createdAt: "19 Sep 2024",
  },
];
